# Generated by Django 4.2.18 on 2026-02-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_comment_options_alter_comment_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='subject',
            field=models.CharField(default='No Subject', max_length=200),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
    ]
