# Generated by Django 4.2.18 on 2026-03-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_comment_subject_comment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.TextField(verbose_name='Въведен текст')),
                ('clean_text', models.TextField(blank=True, null=True, verbose_name='Предобработен текст')),
                ('sentiment', models.CharField(choices=[('positive', 'Позитивен'), ('neutral', 'Неутрален'), ('negative', 'Негативен')], max_length=10, verbose_name='Настроение')),
                ('pos_score', models.FloatField(verbose_name='Вероятност Позитивен')),
                ('neu_score', models.FloatField(verbose_name='Вероятност Неутрален')),
                ('neg_score', models.FloatField(verbose_name='Вероятност Негативен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата на анализ')),
            ],
            options={
                'verbose_name': 'Анализ на отзив',
                'verbose_name_plural': 'Анализи на отзиви',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
